[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
  Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept, Origin, Cache-Control,
  Access-Control-Allow-Headers = "Content-Type"
[build]
  functions = "netlify/functions"